### ISSUE TITLE
Problem with cond implementation of TimeoutCountingSema

### ISSUE THREAD

**Issue by bgmerrell** [tarndt/sema#1]
The below code only appears to work if I use the channel implementation of `TimeoutCountingSema`.  Basically the code keeps a map of `TimeoutCountingSema` objects that are locked with a timeout and then unlocked.

After a minimal amount of investigation, it seems like the first lock (for a given ID) is acquired and the protected function (`fnc`) runs, and then the code to unlock is called and `Do` returns, but then subsequent attempts to acquire the lock for the same ID fail and the code hangs indefinitely.  Just calling `UseChannelBasedImpl()` causes the code to run as expected.

``` go
type redirectJobSynchronizer struct {
    mapLock sync.RWMutex
    // Map of per-originID locks
    idToLock map[int64]sema.TimeoutCountingSema
}

func (this *redirectJobSynchronizer) Do(id int64, fnc func() error) error {
    this.mapLock.RLock()
    idSema, ok := this.idToLock[id]
    this.mapLock.RUnlock()
    if !ok {
        this.mapLock.Lock()
        if idSema, ok = this.idToLock[id]; !ok {
            idSema = sema.NewTimeoutSema(1, 10*time.Second)
            this.idTpLock[id] = idSema
        }
        this.mapLock.Unlock()
    }

    //Aquire lock
    if idSema.P() {
        defer idSema.V()
        return fnc()
    }
    return errors.New("timeout")
```

**Comment by tarndt** [comment]
Thanks, I will take a look. In the meantime users should do as you did and call `UseChannelBasedImpl()`.

**Comment by tarndt** [comment]
This was resolved by removing the `sync.Condition` based solution. Not only did it have this defect, improvements made the Go runtime channel implementation made performance delta with the channel based implementation even smaller and thus it was hard to justify the added complexity.
